name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./pdf-app

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: './pdf-app/package-lock.json'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Upload production build to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./pdf-app/build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write      # Allow the deploy action to create deployments
      id-token: write   # Allow the deploy action to create a JWT
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
